<?php
session_start();
$username=$_POST['username'];
$password=$_POST['password'];
$con=mysqli_connect("localhost","root","");
mysqli_select_db($con,"oslab_phpex1");
$q="select * from userlogin where username='$username'&& password='$password'";
$result=mysqli_query($con,$q);
$num=mysqli_num_rows($result);
if($num==1)
{
$_SESSION['username']=$username;
$_SESSION['check']="valid";
header('location:http://localhost/bitBox/index1.php');
}
else
{
    $_SESSION['check']="invalid";
    header('location:http://localhost/bitBox/index.php');
}	
?>